PatientCard.Web/Controllers/JournalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PatientCard.Model;

namespace PatientCard.Web.Controllers
{
    public class JournalsController : Controller
    {
        private PatientCardContext db = new PatientCardContext();

        // GET: Journals
        public ActionResult Index()
        {
            return View(db.Journals.ToList());
        }

        // GET: Journals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Journal journal = db.Journals.Find(id);
            if (journal == null)
            {
                return HttpNotFound();
            }
            return View(journal);
        }

        // GET: Journals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Journals/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Diagnosis,DateVisit")] Journal journal)
        {
            if (ModelState.IsValid)
            {
                db.Journals.Add(journal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(journal);
        }

        // GET: Journals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Journal journal = db.Journals.Find(id);
            if (journal == null)
            {
                return HttpNotFound();
            }
            return View(journal);
        }

        // POST: Journals/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Diagnosis,DateVisit")] Journal journal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(journal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(journal);
        }

        // GET: Journals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Journal journal = db.Journals.Find(id);
            if (journal == null)
            {
                return HttpNotFound();
            }
            return View(journal);
        }

        // POST: Journals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Journal journal = db.Journals.Find(id);
            db.Journals.Remove(journal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PatientCard.Web/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PatientCard.Model;
using PatientCard.Web.ViewModel;

namespace PatientCard.Web.Controllers
{
    public class PatientsController : Controller
    {
        private PatientCardContext db = new PatientCardContext();

        // GET: Patients
        public ActionResult Index()
        {
            return View(db.Patients.ToList());
        }


        public ActionResult Signup(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            JournalViewModel journalViewModel = new JournalViewModel
            {
                Patient = new PatientViewModel
                {
                    Id = patient.Id,
                    Name = patient.Name,
                    Iin = patient.Iin
                }
            };
            if (journalViewModel == null)
            {
                return HttpNotFound();
            }
            return View(journalViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Signup(JournalViewModel journalViewModel)
        {
            if (ModelState.IsValid)
            {
                Doctor doctor = journalViewModel.Doctor;
                Patient patient = db.Patients.Find(journalViewModel.Patient.Id);
                //Patient patient = new Patient
                //{
                //    Name = journalViewModel.Patient.Name,
                //    Id = journalViewModel.Patient.Id,
                //    Iin = journalViewModel.Patient.Iin
                //};

                var journal = new Journal
                {
                    Diagnosis = journalViewModel.Diagnosis,
                    DateVisit = journalViewModel.DateVisit,
                    Patient = patient,
                    Doctor = doctor
                };

                db.Journals.Add(journal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }


        // GET: Patients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var doctor = db.Doctors.ToList();
            Patient patient = db.Patients.Find(id);
            //Doctor doctor = db.Doctors.Find
            JournalViewModel journalViewModel = new JournalViewModel
            {
                Patient = new PatientViewModel
                {
                    Id = patient.Id,
                    Name = patient.Name,
                    Iin = patient.Iin
                },
            };
            if (journalViewModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.Journals = db.Journals.Where(j => j.Patient.Id == id).ToList() as IEnumerable<Journal>;

            return View(journalViewModel);
        }

        // GET: Patients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Iin")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Patients.Add(patient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: Patients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Iin")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: Patients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient patient = db.Patients.Find(id);
            db.Patients.Remove(patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PatientCard.Web/Views/Patients/Create.cshtml
@model PatientCard.Model.Patient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Iin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Iin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Iin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PatientCard.Web/Views/Patients/Delete.cshtml
@model PatientCard.Model.Patient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Iin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Iin)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PatientCard.Web/Views/Patients/Details.cshtml
@model PatientCard.Web.ViewModel.JournalViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<input id="myInput" type="text" placeholder="Search..">
<br><br>


<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Patient.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patient.Iin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Iin)
        </dd>

    </dl>
</div>

<table class="table" id="myTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Diagnosis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateVisit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doctor.DocName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doctor.Speciality)
        </th>
        <th></th>
    </tr>

    @foreach (var item in (IEnumerable<PatientCard.Model.Journal>)ViewBag.Journals)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Diagnosis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateVisit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Doctor.DocName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Doctor.Speciality)
            </td>
            <td>
                <a href="@Url.Action("Edit","Journals", new { id = item.Id })">Edit</a>|
                <a href="@Url.Action("Delete","Journals", new { id = item.Id })">Delete</a>|
                <a href="@Url.Action("Details","Journals", new { id = item.Id })">Details</a>|
        </tr>
    }

</table>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Patient.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PatientCard.Web/Views/Patients/Edit.cshtml
@model PatientCard.Model.Patient

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Iin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Iin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Iin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PatientCard.Web/Views/Patients/Index.cshtml
@model IEnumerable<PatientCard.Model.Patient>

@{
    ViewBag.Title = "Index";
}


<h2>Index</h2>

<input id="myInput" type="text" placeholder="Search..">
<br><br>


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table" id="myTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Iin)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Iin)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Sign Up", "Signup", new { id = item.Id })
            </td>
        </tr>
    }

</table>

PatientCard.Web/Views/Patients/Signup.cshtml
@model PatientCard.Web.ViewModel.JournalViewModel
@{
    ViewBag.Title = "Patient Journal";
}

<h2>Journal Patient</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Journal</h4>
        <p>@Model.Patient.Name</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Patient.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Diagnosis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Diagnosis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Diagnosis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateVisit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateVisit, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.DateVisit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doctor.DocName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doctor.DocName, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.Doctor.DocName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doctor.Speciality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doctor.Speciality, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.Doctor.Speciality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}